### ISSUE TITLE
报错 CERT_UNTRUSTED

### ISSUE THREAD

**Issue by qdsang** [janpo/meteor-accounts-qq#1]
{"line":"398","file":"oauth_server.js","message":"Error in OAuth Server: Failed to complete OAuth handshake with QQ. CERT_UNTRUSTED","time":{"$date":1425352193559},"level":"warn"}

**Comment by qdsang** [comment]
v0.10.34 node 版本的问题。。。 降到0.10.33 没有问题  顺便问下，大神一般用node什么版本？

**Comment by awesomepan** [comment]
这个需要你根据meteor官方来，有限制的
